### ISSUE TITLE
Seltener Crash bei VideoPlayer

### ISSUE THREAD

**Issue by anExistingGuy** [hasenbalg/VRAusstellung#14]
Sehr selten, wenn im VideoPlayer ein Video loopt, crasht er. Die Timeline läuft dennoch weiter. Geht man dann aus dem Raum und zurück in den Raum, so crasht die Anwendung. Unity loggt keinen Fehler und im AppData-Ordner wo die output.log liegt, im Crashes-Ordner ist ebenfalls nichts vermerkt. Liegt vermutlich nicht an unserem Code.

**Comment by hasenbalg** [comment]
geht jetz
